services:
  - type: web
    name: stagemate
    env: node
    buildCommand: "chmod +x ./build.sh && ./build.sh"
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - client/**
